name: Validate
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Configurations
        uses: devcontainers/action@v1
        with:
          validate-only: true
          base-path-to-features: ./src

      - name: Lint Shell Scripts
        uses: azohra/shell-linter@v0.6.0
        with:
          path: src/**/*.sh
          severity: error  # [style, info, warning, error]
        env:
          SHELLCHECK_OPTS: -e SC2072  # Acceptable use of decimal comparison
